### ISSUE TITLE
ifconfig has been deprecated on Debian

### ISSUE THREAD

**Issue by antsunji** [robier/dokman#5]
As the title says, ifconfig has been deprecated on Debian in favour of ip
https://askubuntu.com/questions/1031640/ifconfig-missing-after-ubuntu-18-04-install

At the moment you can still install it manually, but it may be removed completely in future. Can you add support for ip tool, or add a requisite how to install ifconfig manullay?

**Comment by robier** [comment]
`ifconfig` is replaced by `ip` as you suggested.

Can you please test it locally so we are sure this new implementation works properly?

Steps to setup branch and test locally:

0. go to your project root
0. use `checkout` script inside dokman folder ie. `docker/.dokman/checkout removing-ifconfig`
0. easiest way to check value of `$DOKMAN_HOST_IP` variable is to check parsed YAML configuration with command `docker/env dev config` (for checking dev environment)
0. after testing, and merge you can also use checkout script to checkout dokman to new tag ie. `docker/.dokman/checkout $tag`
